clear all
close all

years = {'2011', '2012', '2013'};

for i = [1:length(years)]
    year = years{i};
    fpath = sprintf('../%s', year);
    files = dir(sprintf('%s/*.mat', fpath));
    for f=[1:length(files)]
        load(sprintf('%s/%s', fpath, files(f).name));
        ntest = length(resp);
        ntrain = length(train_resp);
        type = [repmat('train', ntrain, 1); repmat('test ', ntest, 1)];
        response = [train_resp'; resp'];
        stimulus = [settings.training_items'; settings.quants(1:ntest)'];
        rt1 = [train_rt(:,:,1)'; rt(:,1)];
        rt2 = [train_rt(:,:,2)'; rt(:,2)];
        date = sprintf('%s-%s-%s.%s%s', ...
            exp.dateStr(1:4), ...
            exp.dateStr(5:6), ...
            exp.dateStr(7:8), ...
            exp.dateStr(10:11), ...
            exp.dateStr(12:13));
        filename = sprintf('%s/csv/%s.%s.%s.csv', fpath, exp.name, exp.sid, date);
        fp = fopen(filename, 'w');
        fprintf(fp, '%s,%s,%s,%s,%s,%s,%s,%s',...
            'sid',...
            'year',...
            'date',...
            'type',...
            'stimulus',...
            'response',...
            'rt1',...
            'rt2');
        for j = [1:length(response)]
            line = sprintf('\n%s,%s,%s,%s,%d,%d,%2.3f,%2.3f',...
                exp.sid,...
                year,...
                date,...
                strtrim(type(j,:)),...
                stimulus(j,:),...
                response(j,:),...
                rt1(j,:),...
                rt2(j,:));
            fprintf(fp, '%s', line);
        end
        fclose(fp);
    end
end
        
        